# Generated by Django 4.2.16 on 2024-11-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamictableschema',
            name='table_name',
            field=models.CharField(max_length=255),
        ),
    ]
