# Generated by Django 4.2.16 on 2024-11-19 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_alter_dynamictableschema_table_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255, unique=True)),
                ('schema', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('table_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='testdb.tableschema')),
            ],
        ),
    ]
